<?php

/**
 * @file
 * Contains as_produit.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_produit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_produit module.
    case 'help.page.as_produit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Produits pour AstonShop website') . '</p>';
      return $output;

    default:
  }
}

function as_produit_theme($existing, $type, $theme, $path) {
  return array(
    'produit_list' => array(
      'render_elements' => 'elements',
    ),
  );
}

